name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
      BOT_TOKEN: ${{ secrets.PRODUCTION_BOT_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push

      # Deploy functions with environment variables
      - name: Deploy Function
        run: |
          supabase functions deploy --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt

      # Set up Telegram bot webhooks
      - name: Set up Telegram Bot Webhooks
        run: |
          FUNCTION_URL="https://$SUPABASE_PROJECT_ID.supabase.co/functions/v1/telegram-bot"

          # Set up bot webhook
          curl -X POST "https://api.telegram.org/bot$BOT_TOKEN/setWebhook" \
            -H "Content-Type: application/json" \
            -d "{\"url\": \"$FUNCTION_URL/$BOT_TOKEN\"}"
          echo "Bot webhook set to $FUNCTION_URL/$BOT_TOKEN"
